pipeline {
    agent any
    environment {
        ENV_FILE = credentials('project-env')
        TEST_NETWORK = "jenkins-test-network"
    }
    tools {
        dockerTool 'DefaultDocker'
    }
    stages {
        stage('Setup Environment') {
            steps {
                script {
                    sh 'cp $ENV_FILE ./backend/.env'
                    sh 'cp $ENV_FILE ./frontend/.env'
                }
            }
        }
        stage('Create Test Network') {
            steps {
                script {
                    sh "docker network create ${TEST_NETWORK} || true"
                }
            }
        }
        stage('Backend Build') {
            steps {
                dir('backend') {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew clean build'
                }
            }
        }
        stage('Frontend Build') {
            tools {
                nodejs "NodeJS-20"
            }
            steps {
                dir('frontend') {
                    sh '''
                    npm install
                    npm run build
                    '''
                }
            }
        }
        stage('Docker Compose (Test)') {
            steps {
                script {
                    sh '''
                    docker-compose down || true
                    docker-compose up -d --build --network=${TEST_NETWORK}
                    '''
                }
            }
        }
        stage('Check Running Containers') {
            steps {
                script {
                    sh 'docker ps -a'
                }
            }
        }
        stage('Cleanup Test Network') {
            steps {
                script {
                    sh "docker network rm ${TEST_NETWORK} || true"
                }
            }
        }
    }
}
