pipeline {
    agent any
    environment {
        ENV_FILE = credentials('project-env')
    }
    stages {
        stage('Setup Environment') {
            steps {
                withCredentials([file(credentialsId: 'project-env', variable: 'ENV_FILE')]) {
                    sh '''
                    cp $ENV_FILE ./backend/.env
                    cp $ENV_FILE ./frontend/.env
                    '''
                }
            }
        }
        stage('Backend Build') {
            steps {
                dir('backend') {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew clean build'
                }
            }
        }
        stage('Frontend Build') {
            tools {
                nodejs "NodeJS-20"
            }
            steps {
                dir('frontend') {
                    sh '''
                    npm install
                    npm run build
                    '''
                }
            }
        }
        stage('Docker Compose') {
            steps {
                script {
                    sh '''
                    echo "Stopping and removing old containers if exist..."
                    docker-compose down || true

                    echo "Starting services with Docker Compose..."
                    docker-compose up -d --build

                    echo "Waiting for DB service to be ready..."
                    docker-compose up -d db
                    sleep 15

                    echo "Starting backend and frontend services..."
                    docker-compose up -d backend frontend
                    '''
                }
            }
        }
    }
}
