pipeline {
    agent any
    environment {
        ENV_FILE = credentials('project-env')
    }
    tools {
        dockerTool 'DefaultDocker'
    }
    stages {
        stage('Setup Environment') {
            steps {
                script {
                    sh 'cp $ENV_FILE ./backend/.env'
                    sh 'cp $ENV_FILE ./frontend/.env'
                }
            }
        }
        stage('Check .env') {
            steps {
                script {
                    sh 'cat ./backend/.env || echo ".env file not found in backend"'
                    sh 'cat ./frontend/.env || echo ".env file not found in frontend"'
                }
            }
        }
        stage('Backend Build') {
            steps {
                dir('backend') {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew clean build'
                }
            }
        }
        stage('Frontend Build') {
            tools {
                nodejs "NodeJS-20"
            }
            steps {
                dir('frontend') {
                    sh '''
                    npm install
                    npm run build
                    '''
                }
            }
        }
        stage('Docker Compose') {
            steps {
                script {
                    sh '''
                    docker-compose --env-file ./backend/.env down || true
                    docker-compose --env-file ./backend/.env up -d --build
                    '''
                }
            }
        }
        stage('Check Running Containers') {
            steps {
                script {
                    sh 'docker ps -a'
                }
            }
        }
    }
}
